let quotes = [
  "Be yourself; everyone else is already taken.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "True friends stab you in the front.",
  "Women are made to be Loved, not understood.",
  "Be the change that you wish to see in the world.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "No one can make you feel inferior without your consent.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "Do what you feel in your heart to be right - for you'll be criticized anyway.",
  "Do one thing every day that scares you.",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate; only love can do that.",
  "Our lives begin to end the day we become silent about things that matter.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.",
  "Injustice anywhere is a threat to justice everywhere.",
  "The time is always right to do what is right.",
  "Life's most persistent and urgent question is, 'What are you doing for others?",
  "Weak people revenge. Strong people forgive. Intelligent People Ignore.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Genius is one percent inspiration and ninety-nine percent perspiration.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
  "If we did all the things we are capable of, we would literally astound ourselves.",
  "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "We make a living by what we get, but we make a life by what we give.",
  "Peace begins with a smile.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "If you can't feed a hundred people, then feed just one.",
  "Kind words can be short and easy to speak, but their echoes are truly endless.",
  "Isn't it nice to think that tomorrow is a new day with no mistakes in it yet?",
  "Tomorrow is always fresh, with no mistakes in it.",
  "We should regret our mistakes and learn from them, but never carry them forward into the future with us.",
  "It's so easy to be wicked without knowing it, isn't it?",
  "All the darkness in the world cannot extinguish the light of a single candle.",
  "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
  "Preach the Gospel at all times and when necessary use words.",
  "A single sunbeam is enough to drive away many shadows.",
  "You never fail until you stop trying.",
  "You see things; you say, 'Why?' But I dream things that never were; and I say 'Why not?",
  "We don't stop playing because we grow old; we grow old because we stop playing.",
  "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
  "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
  "Kindness is a language which the deaf can hear and the blind can see.",
  "The secret of getting ahead is getting started.",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Truth is stranger than fiction, but it is because Fiction is obliged to stick to possibilities; Truth isn't.",
  "If you tell the truth, you don't have to remember anything.",
  "I have never met a man so ignorant that I couldn't learn something from him",
  "Earth provides enough to satisfy every man's needs, but not every man's greed.",
  "Where there is love there is life.",
  "Happiness is when what you think, what you say, and what you do are in harmony.",
  "The weak can never forgive. Forgiveness is the attribute of the strong.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.",
  "In a gentle way, you can shake the world.",
  "He that can have patience can have what he will.",
  "Either write something worth reading or do something worth writing.",
  "Tell me and I forget, teach me and I may remember, involve me and I learn.",
  "Never ruin an apology with an excuse.",
  "Early to bed and early to rise makes a man healthy, wealthy and wise.",
  "By failing to prepare, you are preparing to fail.",
  "Those who look for the bad in people will surely find it.",
  "People don't realize how a man's whole life can be changed by one book.",
  "If you have no critics you'll likely have no success.",
  "I'm for truth, no matter who tells it. I'm for justice, no matter who it's for or against.",
  "It is not a lack of Love, but a lack of People that makes unhappy marriages.",
  "He who has a why to live can bear almost any how.",
  "That which does not kill us makes us stronger",
  "To live is to suffer, to survive is to find some meaning in the suffering.",
  "There is always some madness in love. But there is also always some reason in madness.",
  "No price is too high to pay for the privilege of owning yourself.",
  "You know, when it works, Love is amazing. It's not overrated.",
  "Life is an awful, ugly place to not have a best friend.",
  "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
  "Anyone can hide. Facing up to things, working through them, that's what makes you strong.",
  "If you want to live a happy life, tie it to a goal, not to people or things",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Everything around you that you call life was made up by people, and you can change it.",
  "Design is not just what it looks like and feels like. Design is how it works.",
  "Innovation distinguishes between a leader and a follower.",
  "Sometimes life is going to hit you in the head with a brick. Don't lose faith.",
  "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.",
  "A lot of times, people don't know what they want until you show it to them.",
  "Let’s go invent tomorrow rather than worrying about what happened yesterday.",
  "The most precious thing that we all have with us is time.",
  "You have to trust in something, your gut, destiny, life, karma, whatever.",
  "Every child is an artist, the problem is staying an artist when you grow up.",
  "The purpose of art is washing the dust of daily life off our souls.",
  "Good artists copy, great artists steal.",
  "Art is a lie that makes us realize truth.",
  "Inspiration does exist, but it must find you working.",
  "Strive not to be a success, but rather to be of value.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "We learn wisdom from failure much more than from succes.",
  "Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.",
  "We often discover what will do, by finding out what will not do; and probably he who never made a mistake never made a discovery.",
  "Lost wealth may be replaced by industry, lost knowledge by study, lost health by temperance or medicine, but lost time is gone forever.",
  "Life will always be to a large extent what we ourselves make it.",
];
window.onload = main;
function main() {
  // references
  const quoteGenerateBtn = document.getElementById("generate-quote");
  const quoteBody = document.getElementById("quote-body");

  quoteGenerateBtn.addEventListener("click", () => {
    const index = Math.floor(Math.random() * quotes.length);
    const quote = quotes[index];
    quoteBody.innerText = quote;
  });
}
